name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: login to the docker hub
      run: docker login --username "${{ secrets.Docker.username }}" --password "${{ secrets.Docker_password }}"
    - name: build docker image 
      run: docker build . --file Dockerfile --tag krishnaprasadkv/nodejs
    - name: push docker image 
      run: docker push . --file Dockerfile --tag krishnaprasadkv/nodejs
      
      env:
        CI: true
